MoolahConnectnew/ViewModels/Borrower/LoanViewModel.cs
using MoolahConnect.Util.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoolahConnectnew.ViewModels.Borrower
{
    public class LoanViewModel
    {
        public long RequestId { get; set; }
        public double Amount { get; set; }
        public double FinalAmount { get; set; }
        public string Tenor { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime MaturityDate { get; set; }
        public int MonthsTillMaturity { get; set; }
        public double MoolahFees { get; set; }
        public double Rate { get; set; }
        public double EIR { get; set; }
        public double PrincipalPaidTillDate { get; set; }
        public double InterestPaidTillDate { get; set; }
        public double TotalInterestPayable { get; set; }
        public Guid UserId { get; set; }
        public LoanRequestStatus Status { get; set; }

        public string AccountNumber { get; set; }
        public string CompanyName { get; set; }
        public double AmountPaidTillDate { get; set; }

        public string FinalIssuerContractName { get; set; }
        public string FinalGuaranorContractName { get; set; }
    }
}

MoolahConnectnew/ViewModels/Borrower/PaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoolahConnectnew.ViewModels.Borrower
{
    public class PaymentViewModel
    {
        public long LoanRequestId { get; set; }
        public double Amount { get; set; }
        public DateTime? DueDate { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    }
}

MoolahConnectnew/ViewModels/Loan/LoanRepaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MoolahConnectnew.ViewModels
{
    public class LoanRepaymentViewModel
    {
        public long LoanId { get; set; }
        public long RepaymentId { get; set; }
        public string AccountNumber { get; set; }
        public string CompanyName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public double Amount { get; set; }
        public double Rate { get; set; }
        public int MonthsTillMaturity { get; set; }
        public double MonthlyRepayment { get; set; }
        public DateTime RepaymentDate { get; set; }
        public string Status { get; set; }
        public int StatusRef { get; set; }
        public string Comment { get; set; }

        public DateTime LastUnpaidDueDate { get; set; }
        public double AccuredInterest { get; set; }
        public bool AccuredInterestPaid { get; set; }
        public DateTime? AccuredInterestPaidDate { get; set; }
        public int LateDaysCount { get; set; }

        public double TotalOutstandingRepayments { get; set; }
        public double LateFees { get; set; }
        public bool LateFeesPaid { get; set; }
        public double Paidamount { get; set; }
    }
}

MoolahConnectnew/ViewModels/Loan/LoanRequestViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MoolahConnectnew.ViewModels
{
    public class LoanRequestViewModel
    {
        public LoanRequestViewModel()
        {
            
        }

        public long RequestId { get; set; }
        public int LoanPurposeId { get; set; }

        public decimal Amount { get; set; }

        [DisplayName("Amount")]
        public decimal AcceptedAmount { get; set; }

        [DisplayName("Tenor (Months)")]
        public string Term { get; set; }

        [DisplayName("Target EIR")]
        public decimal EIR { get; set; }

        [DisplayName("Target Rate (% p.a.)")]
        public decimal Rate { get; set; }

        [DisplayName("Video Description")]
        public string VideoDescription { get; set; }

        [DisplayName("Detailed Company Profile")]
        public string DetailedCompanyProfile { get; set; }

        [DisplayName("Headline")]
        public string Headline { get; set; }

        [DisplayName("Summary Company Profile")]
        public string SummaryCompanyPro { get; set; }

        [DisplayName("Purpose")]
        public string LoanPurpose { get; set; }

        
        public string PurchaseValue { get; set; }

        [DisplayName("Personal Guarantee")]
        public bool PersonalGurantee { get; set; }

        [DisplayName("Moolah Sense Comments")]
        public string MoolahSenseComments { get; set; }

        public int UserId { get; set; }

        public string CompanyName { get; set; }
        public string Reference { get; set; }
        public string RegisteredAddress { get; set; }
        public decimal? AverageRate { get; set; }
        public int Days { get; set; }
        public int Hours { get; set; }
        public int Minutes { get; set; }
        public decimal? Funded { get; set; }

        public string LoanPurposeAnswer { get; set; }

        [DisplayName("Number of Employees")]
        public int NoOfEmployees { get; set; }

        public int LoanStatus { get; set; }
        public int PreliminaryStatus { get; set; }

        public DateTime? PublishedDate { get; set; }
    }
}

MoolahConnectnew/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using MoolahConnect.Services.Entities;
using MoolahConnect.Services.Implementation;
using MoolahConnect.Services.Interfaces;
using MoolahConnect.Tasks.Implementation;
using MoolahConnect.Tasks.Interfaces;
using MoolahConnect.Util.Enums;
using MoolahConnect.Util.Logging;
using MoolahConnect.Util.SealedClasses;
using MoolahConnectClassLibrary.DAL;
using MoolahConnectnew.ViewModels;
using MoolahConnectnew.Providers;
using MoolahConnect.Util;

namespace MoolahConnectnew.Controllers
{
    public class SharedController : Controller
    {
        private ILoanPaymentsTask _ILoanPaymentsTask;
        private IFileUploadDA _IFileUploadDA;
        private IFileUploadTask _IFileUploadTask;
        ITransactionsDA _ITransactionDA;
        private IBorrowerLoanDetailsDA _IBorrowerLoanDetailsDA;
        private ILoanAllocationDA _ILoanAllocationDA;
        private ILoanDetailsDA _ILoanDetailsDA;
        ILoanDetailsTask _ILoanDetailsTask;

        public SharedController()
        {
            _ILoanPaymentsTask = new LoanPaymentsTask();
            _IFileUploadDA = new FileUploadDA();
            _IFileUploadTask = new FileUploadTask();
            _ITransactionDA = new TransactionsDA();
            _IBorrowerLoanDetailsDA = new BorrowerLoanDetailsDA();
            _ILoanAllocationDA = new LoanAllocationDA();
            _ILoanDetailsDA = new LoanDetailsDA();
            _ILoanDetailsTask = new LoanDetailsTask();
        }

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult _RepaymentSchedule(long requestID, double amount, double rate, string term, DateTime startDate)
        {
            var model = Mapper.Map<IEnumerable<RepaymentEntity>, IEnumerable<RepaymentViewModel>>(
                _ILoanPaymentsTask.GetRepaymentSchedule(requestID, amount, rate, term, startDate)).ToList();
            ViewBag.RepaymentMessages = _ILoanPaymentsTask.GetRepaymentMessageses(requestID);
            return PartialView(model);
        }

        public PartialViewResult _InvestorRepaymentScheduleFromRequestID(long requestID, double amount, double rate, string term, DateTime startDate)
        {
            var model = Mapper.Map<IEnumerable<RepaymentEntity>, IEnumerable<RepaymentViewModel>>(
                _ILoanPaymentsTask.GetRepaymentSchedule(requestID, amount, rate, term, startDate, true)).ToList();
            ViewBag.RepaymentMessages = _ILoanPaymentsTask.GetRepaymentMessageses(requestID);
            return PartialView("_RepaymentScheduleInv", model);
        }

        public PartialViewResult _RepaymentScheduleFromRequestID(long requestID)
        {
            var model = Mapper.Map<IEnumerable<RepaymentEntity>, IEnumerable<RepaymentViewModel>>(
                _ILoanDetailsDA.GetRepaymentsByRequestID(requestID)).ToList();

            return PartialView("_RepaymentSchedule", model);
        }

        /// <summary>
        /// Method for checking business registration number availability in registered users list
        /// </summary>
        /// <param name="BusinessRegistrationnumber"></param>
        /// <returns></returns>
        public JsonResult CheckBusinessRegNumberAvailbilty(string BusinessRegistrationnumber)
        {
            return Json(ContollerExtensions.CheckBusinessRegNumberAvailbilty(BusinessRegistrationnumber));
        }

        public string Upload(HttpPostedFileBase FileData, FileType type, string username, long? requestId = null, bool multi = true)
        {
            if (string.IsNullOrEmpty(username))
            {
                ViewData["error"] = StatusMessages.SYSTEM_ERROR;
                return StatusMessages.FAILED;
            }

            var user = Membership.GetUser(username);

            if (user == null)
            {
                ViewData["error"] = StatusMessages.SYSTEM_ERROR;
                return StatusMessages.FAILED;
            }

            Guid userId = (Guid)user.ProviderUserKey;

            if (_IFileUploadTask.Upload(userId.ToString(), type.ToString(),
                FileData.FileName, FileData.InputStream,
                requestId.HasValue ? requestId.ToString() : null))
            {


                if (user == null ||
                    !_IFileUploadDA.InsertUploadedFile(FileData.FileName, type,
                    userId, requestId, null, multi))
                {
                    ViewData["error"] = StatusMessages.SYSTEM_ERROR;
                    return StatusMessages.FAILED;
                }

                return StatusMessages.SUCCESS;
            }
            else
            {
                ViewData["error"] = StatusMessages.FILE_UPLOAD_FAILED;
                return StatusMessages.FAILED;
            }
        }

        public ActionResult DownloadFile(Guid userId, FileType type, string fileName, long? requestId = null, int? offerId = null)
        {
            var blob = _IFileUploadTask.Download(userId.ToString(), type.ToString(), fileName,
                requestId.HasValue ? requestId.ToString() : null,
                offerId.HasValue ? offerId.ToString() : null);

            if (blob != null)
            {
                return File(blob.FileStream, blob.ContentType, fileName);
            }
            else return null;
        }

        public ActionResult DownloadFileFromFileName(string filePath)
        {
            var blob = _IFileUploadTask.Download(filePath);

            if (blob != null)
            {
                return File(blob.FileStream, blob.ContentType, filePath);
            }
            else return null;
        }

        public JsonResult DeleteFile(int fileId, string fileName, FileType type, Guid userId, List<string> comments, long? requestId = null)
        {
            if (!_IFileUploadTask.Delete(userId.ToString(), type.ToString(), fileName,
                requestId.HasValue ? requestId.ToString() : null))
                return Json(new { Status = StatusMessages.FAILED }, JsonRequestBehavior.AllowGet);

            _IFileUploadDA.DeleteFile(fileId);
            _IFileUploadDA.UpdateUploadedFileComments(comments);
            return Json(new { Status = StatusMessages.SUCCESS }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult _FilesList(string username, FileType type, string uniqueId, long? requestId = null, string comments = null)
        {
            if (!string.IsNullOrEmpty(comments))
            {

                var idComments = new List<string>();

                var items = comments.Split(',');

                foreach (string item in items)
                {
                    idComments.Add(item.Replace(":", ","));
                }

                _IFileUploadDA.UpdateUploadedFileComments(idComments);
            }

            var model = new List<FileModel>();

            var user = Membership.GetUser(username);

            if (user != null)
            {
                model = Mapper.Map<IEnumerable<tbl_Files>, IEnumerable<FileModel>>(
                    _IFileUploadDA.GetFilesFromUserIdAndTypeAndRequestId((Guid)user.ProviderUserKey, type, requestId)).ToList();
            }

            ViewBag.UniqueId = uniqueId;
            return PartialView(model);
        }

        public PartialViewResult _YouTubeLinksList(long requestId, string comments = null)
        {
            if (!string.IsNullOrEmpty(comments))
            {

                var idComments = new List<string>();

                var items = comments.Split(',');

                foreach (string item in items)
                {
                    idComments.Add(item.Replace(":", ","));
                }

                _IFileUploadDA.UpdateUploadedFileComments(idComments);
            }

            var model = new List<FileModel>();

            model = Mapper.Map<IEnumerable<tbl_Files>, IEnumerable<FileModel>>(
                _IFileUploadDA.GetFilesByRequestId(requestId)).Where(x => x.Type == FileType.YouTubeLink).ToList();

            return PartialView(model);
        }

        public JsonResult AddYouTubeLink(string link, string username, long requestId)
        {
            if (_IBorrowerLoanDetailsDA.AddYouTubeLink(link, username, requestId))
            {
                return Json(new { Status = StatusMessages.SUCCESS }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Status = StatusMessages.FAILED }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DeleteYouTubeLink(int id, List<string> comments)
        {
            if (_IFileUploadDA.DeleteFile(id))
            {
                _IFileUploadDA.UpdateUploadedFileComments(comments);
                return Json(new { Status = StatusMessages.SUCCESS }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Status = StatusMessages.FAILED }, JsonRequestBehavior.AllowGet);
            }
        }

        #region AllLoanTransactinofInvestor
        public ActionResult LoanTransactions()
        {
            var model = new List<TransactionViewModel>();

            model = Mapper.Map<IEnumerable<tbl_LoanTransactions>, IEnumerable<TransactionViewModel>>(
                _ITransactionDA.GetTransactionbyUser(User.Identity != null ? User.Identity.Name : string.Empty))
                .ToList();

            return View(model);
        }

        public PartialViewResult _Transactions(string from, string to)
        {
            DateTime? _from = null;
            DateTime? _to = null;

            try
            {
                _from = DateTime.ParseExact(from, "dd/MM/yyyy", null);
                _to = DateTime.ParseExact(to, "dd/MM/yyyy", null);
            }
            catch (Exception ex)
            {

MoolahConnectnew/Views/Borrower/ActionLogs.cshtml
@using MoolahConnectnew.ViewModels
@using MoolahConnect.Util.ExtensionMethods
@model IEnumerable<AuditLogViewModel>
@{
    ViewBag.Title = "Action Logs";
}

<div id="wish" class="no_bg pad_10 no_mar_bot">

    <div class="dash_board">
        <div class="dash_board_in">
            <div id="live">
                <div>
                    <div class="h5_title">Your Action logs</div>
                    @MoolahConnectHelper.DateTimeRangePicker("liDatePickerFrom", "liDatePickerTo", "SearchActionLogs")
                </div>
                <div id="divLogs" class="event_in" style="border: none">
                    @Html.Partial("_Logs", Model)
                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>

</div>

<script>
    function SearchActionLogs(_from, _to) {
        $('#divLogs').empty();
        $('#divLogs').load('/Borrower/_Logs?from=' + _from + '&to=' + _to);
    }
</script>

MoolahConnectnew/Views/Borrower/ConfirmRegistration.cshtml
@{
    ViewBag.Title = "Confirm Registration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div style="width: 100%" align="center">
        <img alt="" src="/Content/images/logo.png">
        <div class="ConfMessage">
            Thank you for successfully submitting your information. We are reviewing the information and shall be getting back to you within one business day (typically sooner) with regards to your registration status.
            <br />
            <br />
            In the meantime, if you have any queries, please do not hesitate to contact us at +65-6871-8780.
        </div>
    </div>
</div>

MoolahConnectnew/Views/Borrower/Create.cshtml
@model MoolahConnectClassLibrary.Models.ViewModels.BorrowerAccount

@{
    ViewBag.Title = "Account Info";
}

@using MoolahConnectnew
@Html.Flash()

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<style>
    label {
        display: inline-block;
        width: 5em;
    }

        html ul.tabs li:hover, html ul.tabs li:hover a
{
    background: #f3f1e5;
    font-weight:normal;
}

        html ul.tabs li.active, html ul.tabs li.active a
{
    color: #fff;
    font-weight: bold;
    background: #ffbe3a;
    border-bottom: 1px solid #fff;
    border-radius: 5px 5px 0 0;
    -moz-border-radius: 5px 5px 0 0;
    -ms-border-radius: 5px 5px 0 0;
    -o-border-radius: 5px 5px 0 0;
    -webkit-border-radius: 5px 5px 0 0;
    -khtml-border-radius: 5px 5px 0 0;
    border-left: 1px solid #BBB9AF;
}
</style>
<script>
    $(function () {
        $(document).tooltip();
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        if($('#hdnQest2').val()!='0')        
            $('#ddlSq2').val($('#hdnQest2').val());
        else
            $('#ddlSq2').val('2');
        
        //Default Action
        $(".tab_content").hide(); //Hide all content
        if (@Session["step"] == 1) {           
            $("ul.tabs li:first").addClass("active").show(); //Activate first tab
            $(".tab_content:first").show(); //Show first tab content

        }
        else if (@Session["step"] == 2) {           
            $("ul.tabs li:first").next().addClass("active").show(); //Activate first tab
            $(".tab_content:first").next().show(); //Show first tab content

        }
        else if (@Session["step"] == 3) {  
           
            $("ul.tabs li:last").addClass("active").show(); //Activate first tab
            $(".tab_content:last").show(); //Show first tab content

        }

        $('.print_form').click(function () {
            GetPDFforRegistrationform();
        });
    });

    function GetPDFforRegistrationform()
    {
        window.location='@Url.Action("GeneratePDFforRegistrationform", "Borrower")';
    }

    function GotoStep(step,ispostback) {
        
        $("ul.tabs li").removeClass("active"); //Remove any "active" class
        $(".tab_content").hide(); //Hide all content
     
        if (step == null) {
            @{
                Session["step"] = null;
            }
        }
        if (step == 1) {
            @{Session["step"] = 1;}
            $("ul.tabs li:first").addClass("active").show(); //Activate first tab
            $(".tab_content:first").show(); //Show first tab content
           
        }
        else if (step == 2) {
        
            @{Session["step"] = 2;}
      
            $("ul.tabs li:first").next().addClass("active").show(); //Activate first tab
            $(".tab_content:first").next().show(); //Show first tab content
        
        }
        else if (step == 3) {
       
            @{Session["step"] = 3;}
       
            $("ul.tabs li:last").addClass("active").show(); //Activate first tab
            $(".tab_content:last").show(); //Show first tab content
            
        }      
       
        if(ispostback==true)
        {
            window.location='@Url.Action("Create", "Issuer")';
        }
        return false;
    }

</script>

<div class="container">
    @if (Model.BorrowerAccountDetailsModel.SecurityQuestion2 > 0)
    {
        <input id="hdnQest2" type="hidden" value="@Model.BorrowerAccountDetailsModel.SecurityQuestion2" />
    }
    else
    {
        <input id="hdnQest2" type="hidden" value="0" />
    }
    <ul class="tabs">
        <li id="tabs1" class="1" ><a style="cursor: default;">Step 1: Account Details</a></li>
        <li id="tabs2" class="1" ><a style="cursor: default;">Step 2: Print & Submit</a></li>
    </ul>
    <div class="tab_container">
        <div id="tab1" class="tab_content">
            @Html.Partial("_borrowerAccount", Model.BorrowerAccountDetailsModel);
        </div>
        <div id="tab2" class="tab_content">
            @Html.Partial("_borrowerSavedocuments", Model.BorrowerDocuments);
        </div>
    </div>
</div>

MoolahConnectnew/Views/Borrower/_OutstandingPayments.cshtml
@using MoolahConnectnew.ViewModels.Borrower
@using MoolahConnect.Util.Enums
@using MoolahConnect.Util.SealedClasses
@using MoolahConnect.Util.ExtensionMethods

@model IEnumerable<PaymentViewModel>

<table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr class="bg_col">
                    <td class="bdr_bottom bdr_left">Note ID</td>
                    <td class="bdr_bottom">Monthly Repayment  </td>
                    <td class="bdr_bottom">Due Date  </td>
                    <td class="bdr_bottom">Status</td>
                    <td class="bdr_bottom">Note </td>
                </tr>

                @if (Model.Count() > 0)
                {
                    foreach (PaymentViewModel item in Model)
                    {
                    <tr>
                        <td class="bdr_left bdr_bottom">@Html.ActionLink(item.LoanRequestId.ToString(), "MatchedNoteDetails", "Note", new { noteRequestID = item.LoanRequestId }, new { target = "_blank" })</td>
                        <td class="bdr_bottom">@item.Amount.ToCurrency()  </td>
                        <td class="bdr_bottom">@item.DueDate.ToDate()</td>
                        <td class="bdr_bottom">@item.Status</td>
                        <td class="bdr_bottom">@item.Note  </td>
                    </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="bdr_left bdr_bottom" colspan="5">No Outstanding Payments</td>

                    </tr>
                }
            </table>

MoolahConnectnew/Views/Borrower/_ReviewandSubmit.cshtml
<span style="font:bold;font-size:15px;padding:15px 0 15px 5px;float:left">Loan request submitted successfully</span>

MoolahConnectnew/Views/Borrower/_borrowerSavedocuments.cshtml
@using MoolahConnect.Util.Enums
@model MoolahConnectClassLibrary.Models.ViewModels.BorrowerDocuments

<div id="wish" class="no_bg">
    <div class="wish_txt_in min_width_1">
        <b><u>Compulsory Supporting Documents</u></b>
        <br />
        <br />
        1)	Certified true copy of the latest ACRA Bizfile business profile report
        <br />
        <br />
        2) Certified true copy of the Limited Liability Partnership Agreement/Memorandum & Articles of Association (M&A)
        <br />
        <br />
        3)	Proof of identity of directors/partners/managing partner
        <br />
        <br />
        Certified true copies of identity card/passport of all the authorised directors/partners/managing partner in the Resolution
        <br />
        <br />
        <b>Singaporeans and Permanent Residents (PR)</b>
        <br />
        <br />
        &nbsp&nbsp 1.	Photocopy of front and back of identity card 
        <br />
        <br />
        <b>Foreigners without PR Status</b>
        <br />
        <br />
        &nbsp&nbsp 1.	Photocopy of valid passport(At least 6 months validity)
        <br />
        &nbsp&nbsp 2.	Photocopy of employment pass, dependant’s pass or student pass
        <br />
        <br />
        4)	Proof of residential address of all the authorised directors/partners/managing partner in the Resolution (dated within 6 months)
        <br />
        <br />
        Provide a photocopy of any <b>ONE</b> of the following documents:
        <br />
        &nbsp&nbsp -	Bank statement<br />
        &nbsp&nbsp -	Credit card statement<br />
        &nbsp&nbsp -	Utility bill<br />
        &nbsp&nbsp -	Rental agreement<br />
        &nbsp&nbsp -	Singapore government/government agency statement (IRAS/CPF/CDP/SAF)<br />
        <br />
        5)	A corporate bank account with a local bank or foreign qualifying full bank in Singapore. 
        <br />
        <br />
        Provide photocopies of the following documents:
        <br />
        <table style="margin-left:10px;">
            <tr>
                <td style="vertical-align:text-top">-&nbsp</td>
                <td style="vertical-align:text-top">Latest 3 months bank statements that indicate the account holder’s name, local trading address and account number.</td>
            </tr>
            <tr>
                <td style="vertical-align:text-top">-&nbsp</td>
                <td style="vertical-align:text-top">If local trading address is not available on the bank statements, please provide utility bill (dated within 6 months) in addition to the bank statements as proof of local trading address.</td>
            </tr>
        </table>
        <br />
        <br />
        6)	Latest financial statements (Preferably 2 years of audited statements)
        <br />
        <br />
        <div class="register-div">
            <b>Certification of true copies for Private Limited</b><br />
            Photocopied documents must be certified true by signature from company director or company secretary.
            <br />
            Directors cannot certify own documents.<br />
            Certified exact of resolution must be certified true copies by 2 directors or 1 director and company secretary<br />
            <br />
            <br />
            <b>Certification of true copies for LLP</b><br />
            Photocopied documents must be certified true by signature from any one partners.
            <br />
            Partners cannot certify own documents<br />
            Certified exact of resolution must be certified true copies by at least 2 partners<br />
        </div>
        <br />
        <br />
        <b><u>Procedure</u></b>
        <br />
        <br />
        1)	Print, sign and scan the <b>Standard Terms and Conditions </b>
        <br />
        2)	Print, sign and scan the <b>Partners’ Resolution/Directors’ Resolution</b><br />
        3)	Upload the signed <b>Standard Terms and Conditions </b>, <b>Partner’s Resolution/Director’s Resolution</b> and <b>Compulsory Supporting Documents</b>
        <br />
        4)	Submit the application<br />
        5)	Receive an email from MoolahSense once the application has been processed<br />
        <br />
        <br />

    </div>
    <div class="fr">
        <table>
            <tr>
                <td><a href="@Url.Action("DownloadFileFromFileName", "Shared", new { filePath = "MSense - Issuer Standard TC.pdf" })">
                    <input name="" type="button" class="print_form" value="Print Standard Terms and Conditions"></a></td>
            </tr>
            <tr>
                <td><a href="@Url.Action("DownloadFileFromFileName", "Shared", new { filePath = "Issuer Partners' Resolution.pdf" })">
                    <input name="" type="button" class="print_form" value="Print Partners' Resolution"></a></td>
            </tr>
            <tr>
                <td><a href="@Url.Action("DownloadFileFromFileName", "Shared", new { filePath = "Issuer Directors' Resolution.pdf" })">
                    <input name="" type="button" class="print_form" value="Print Directors' Resolution"></a></td>
            </tr>
        </table>
    </div>
    <div class="clear"></div>
    <div style="width: 50%">
        @MoolahConnectHelper.UploadRegistrationDocuments("doc", "Documents Upload", HttpContext.Current.User.Identity.Name, FileType.Registration.ToString(), "false")
    </div>
    <br />
    <div id="divTerms">
        <b>I have read and understood the contents in the following documents:</b>
        <br />
        <br />
        <input type="checkbox" onclick="CheckAllOptions('borRules', this.checked);" />&nbsp Select All
        <br />
        <input type="checkbox" class="borRules" id="cbTerms1" />&nbsp&nbsp<a target="_blank" href="http://www.moolahsense.com/wp-content/uploads/2014/09/MSense-Standard-TC.pdf">Standard Terms and Conditions </a>
        <br />
        <input type="checkbox" class="borRules" id="cbTerms2" />&nbsp&nbsp<a target="_blank" href="http://www.moolahsense.com/wp-content/uploads/2014/09/MSense-Code-of-Conduct.pdf">Code of Conduct </a>
        <br />
        <input type="checkbox" class="borRules" id="cbTerms3" />&nbsp&nbsp<a target="_blank" href="http://www.moolahsense.com/wp-content/uploads/2014/09/MSense-Privacy-and-Data-Protection-Policy.pdf">Privacy and Data Protection Policy </a>
        <br />
        <b>I declare that the above information provided by me is true and accurate.</b>
    </div>
    <div class="pre-next-buttons-submit">
        <input name="" type="button" class="wish_btn_back" value="Back" onclick="GotoStep(1, false)">
        <input name="" type="button" class="wish_btn next-btn" value="Submit" onclick="ClickSubmit('Borrower', 'doc')">
    </div>
</div>